<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="TExampleInterfaceImplementation" Id="{f249db92-7f44-46a0-b7fe-a467b8ef1444}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TExampleInterfaceImplementation IMPLEMENTS IExampleInterface
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>